### ISSUE TITLE
Smartbar addition: keep moving cursor when input arrows are held pressed down

### ISSUE THREAD

**Issue by halfbytecode** [AOSiP/platform_packages_apps_DUI#1]
I really like this ROM. I would appreciate if you could merge this new commit from DU.

https://github.com/DirtyUnicorns/android_packages_apps_DUI/commit/c196b8cc14852ccc1629b7f9b88730947204135c

**Comment by xlxfoxxlx** [comment]
https://review.aosiprom.com/#/c/AOSIP/platform_packages_apps_DUI/+/3869/

**Comment by halfbytecode** [comment]
Thank you. I really appreciate it.
